In [1]:
import numpy as np
import pandas as pd

import time

import matplotlib.pyplot as plt
import os
import re
import seaborn as sns

In [2]:
from scipy.stats import moment
from scipy.stats import describe

In [3]:
import json
import time
import re

In [4]:
def df_lambda_replace_characters(df, column_name, new_column, dictionary):
    df[new_column] = df[column_name].apply(lambda x: replace_words(x, dictionary))       
    return df

In [5]:
def replace_words(strtext, dictionary):
    pattern = re.compile(r'(?<!\w)(' + '|'.join(re.escape(key) for key in dictionary.keys()) + r')(?!\w)')
    result = pattern.sub(lambda x: dictionary[x.group()], strtext)
    return result

In [6]:
with open("../replacement_dictionary_ordered.json") as json_file:
    replacement_dictionary_2 = json.load(json_file)

In [7]:
import nltk
nltk.download('brown')

[nltk_data] Downloading package brown to /home/cdsw/nltk_data...
[nltk_data]   Package brown is already up-to-date!

True

In [8]:
from textblob import TextBlob

In [9]:
from scipy.stats import moment
from scipy.stats import describe

In [10]:
def basic_stats_error(datalist):
    
    if len(datalist)>1:
        result_describe = list(describe(datalist)[2:])
        result_percentile = result_describe + list(np.percentile(datalist,[10,25,50,75,90]))
        array = np.array(datalist)
        result_percentile = result_percentile+[len(array),len(array[np.where(array>0)[0]])/len(array)*100,
                                               len(array[np.where(array<0)[0]])/len(array)*100]
    else:
        result_percentile = []

    return result_percentile

In [11]:
def explode(df, lst_cols, fill_value=''):
    # make sure `lst_cols` is a list
    if lst_cols and not isinstance(lst_cols, list):
        lst_cols = [lst_cols]
    # all columns except `lst_cols`
    idx_cols = df.columns.difference(lst_cols)

    # calculate lengths of lists
    lens = df[lst_cols[0]].str.len()

    if (lens > 0).all():
        # ALL lists in cells aren't empty
        return pd.DataFrame({
            col:np.repeat(df[col].values, df[lst_cols[0]].str.len())
            for col in idx_cols
        }).assign(**{col:np.concatenate(df[col].values) for col in lst_cols}) \
          .loc[:, df.columns]
    else:
        # at least one list in cells is empty
        return pd.DataFrame({
            col:np.repeat(df[col].values, df[lst_cols[0]].str.len())
            for col in idx_cols
        }).assign(**{col:np.concatenate(df[col].values) for col in lst_cols}) \
          .append(df.loc[lens==0, idx_cols]).fillna(fill_value) \
          .loc[:, df.columns]

In [12]:
import seaborn as sns

In [13]:
sns.set(style="whitegrid")

In [14]:
from importlib import reload

from nlp_pandas_functions import ngram_analysis
from nlp_pandas_functions import noun_sentences

reload(ngram_analysis)
reload(noun_sentences)
dir(ngram_analysis)

2022-05-31 22:17:25,501 loading file /home/cdsw/.flair/models/sentiment-en-mix-distillbert_4.pt

INFO:absl:Using /tmp/tfhub_modules to cache modules.

module https://tfhub.dev/google/universal-sentence-encoder/4 loaded
module https://tfhub.dev/google/universal-sentence-encoder/4 loaded

['__builtins__',
 '__cached__',
 '__doc__',
 '__file__',
 '__loader__',
 '__name__',
 '__package__',
 '__spec__',
 'bigrams_join',
 'count_n_grams',
 'defaultdict',
 'df_get_n_grams_count',
 'df_lambda_ngram',
 'generate_n_grams',
 'get_imp',
 'get_n_grams_count',
 'get_n_grams_probability',
 'kg',
 'ngrams',
 'np',
 'pd',
 'text']

In [15]:
column = 'clean_publicremarks'

In [16]:
#from nlp_pandas_functions import ngram_analysis
from nlp_pandas_functions import noun_sentences

#reload(ngram_analysis)
reload(noun_sentences)
#dir(ngram_analysis)

module https://tfhub.dev/google/universal-sentence-encoder/4 loaded

In [17]:
import glob
filtered_files = glob.glob("new_avm_df__full_data_state_*_noun_sentences.fea")

In [38]:
filtered_files

['new_avm_df__full_data_state_KS_noun_sentences.fea',
 'new_avm_df__full_data_state_AZ_noun_sentences.fea',
 'new_avm_df__full_data_state_TN_noun_sentences.fea',
 'new_avm_df__full_data_state_FL_noun_sentences.fea',
 'new_avm_df__full_data_state_GA_noun_sentences.fea',
 'new_avm_df__full_data_state_OK_noun_sentences.fea',
 'new_avm_df__full_data_state_UT_noun_sentences.fea',
 'new_avm_df__full_data_state_ME_noun_sentences.fea',
 'new_avm_df__full_data_state_CA_noun_sentences.fea',
 'new_avm_df__full_data_state_MS_noun_sentences.fea',
 'new_avm_df__full_data_state_WA_noun_sentences.fea',
 'new_avm_df__full_data_state_OH_noun_sentences.fea',
 'new_avm_df__full_data_state_MA_noun_sentences.fea',
 'new_avm_df__full_data_state_AL_noun_sentences.fea',
 'new_avm_df__full_data_state_NC_noun_sentences.fea',
 'new_avm_df__full_data_state_CO_noun_sentences.fea',
 'new_avm_df__full_data_state_MO_noun_sentences.fea',
 'new_avm_df__full_data_state_KY_noun_sentences.fea',
 'new_avm_df__full_data_state_NE_noun_sentences.fea',
 'new_avm_df__full_data_state_NY_noun_sentences.fea',
 'new_avm_df__full_data_state_VA_noun_sentences.fea',
 'new_avm_df__full_data_state_MD_noun_sentences.fea',
 'new_avm_df__full_data_state_HI_noun_sentences.fea',
 'new_avm_df__full_data_state_WV_noun_sentences.fea',
 'new_avm_df__full_data_state_MN_noun_sentences.fea',
 'new_avm_df__full_data_state_AK_noun_sentences.fea',
 'new_avm_df__full_data_state_IN_noun_sentences.fea',
 'new_avm_df__full_data_state_PA_noun_sentences.fea',
 'new_avm_df__full_data_state_SC_noun_sentences.fea',
 'new_avm_df__full_data_state_LA_noun_sentences.fea',
 'new_avm_df__full_data_state_NJ_noun_sentences.fea',
 'new_avm_df__full_data_state_RI_noun_sentences.fea',
 'new_avm_df__full_data_state_WY_noun_sentences.fea',
 'new_avm_df__full_data_state_TX_noun_sentences.fea']

In [18]:
from nlp_pandas_functions import nlp_pandas_functions
reload(nlp_pandas_functions)
dir(nlp_pandas_functions)

['PorterStemmer',
 'SnowballStemmer',
 'TextBlob',
 'WordNetLemmatizer',
 '__builtins__',
 '__cached__',
 '__doc__',
 '__file__',
 '__loader__',
 '__name__',
 '__package__',
 '__spec__',
 'define_stop_words',
 'df_column_prepare',
 'df_column_remove_punctuation',
 'df_column_remove_unicode',
 'df_column_simple_prepare',
 'df_column_stemmer',
 'df_lambda_lemmatizer',
 'df_lambda_remove_punctuation',
 'df_lambda_remove_stop_words',
 'df_lambda_remove_unicode',
 'df_lambda_stemmer',
 'df_lambda_to_lowercase',
 'df_spell_check',
 'nltk',
 're',
 'single_entry_lambda_stemmer',
 'single_entry_lemmatizer',
 'single_entry_prepare',
 'single_entry_remove_punctuation',
 'single_entry_remove_stop_words',
 'single_entry_remove_unicode',
 'single_entry_spell_check',
 'string',
 'word_tokenize']

In [19]:
for file in filtered_files:
    
    print(file)    
    
    noun_sentence_df_T_ri_filtered = pd.read_feather(file)
    print(len(noun_sentence_df_T_ri_filtered))
    
    noun_sentence_df_T_ri_filtered = noun_sentence_df_T_ri_filtered[noun_sentence_df_T_ri_filtered['count'] > \
                                                                    noun_sentence_df_T_ri_filtered['count'].max()*0.005]
    noun_sentence_df_T_ri_filtered = df_lambda_replace_characters(noun_sentence_df_T_ri_filtered,  'noun_sentence', 
                                                   'noun_sentence_corrections', replacement_dictionary_2)
    noun_sentence_df_T_ri_filtered = noun_sentence_df_T_ri_filtered.drop(columns=['noun_sentence'])
    
    noun_sentence_df_T_ri_filtered = nlp_pandas_functions.df_lambda_remove_unicode(noun_sentence_df_T_ri_filtered,\
                                                                                   'noun_sentence_corrections', 'noun_sentence')

    noun_sentence_df_T_ri_filtered = noun_sentence_df_T_ri_filtered.drop(columns=['noun_sentence_corrections'])
    #noun_sentence_df_T_ri_filtered = noun_sentence_df_T_ri_filtered.\
    #                                                rename(columns={'noun_sentence_corrections':'noun_sentence'})
    
    file_join = file.split('.')[0] + '_filtered_noun_sentences_errors_CJ.csv'
    noun_sentence_df_T_ri_filtered.to_csv(file_join)    
    
    noun_sentence_df_T_ri_filtered_thu = noun_sentence_df_T_ri_filtered.loc[:,['noun_sentence','Listingid_List']]
    noun_sentence_df_T_ri_filtered_thu_list = explode(noun_sentence_df_T_ri_filtered_thu,
                                           lst_cols=['Listingid_List'])
    noun_sentence_df_T_ri_filtered_thu_list = noun_sentence_df_T_ri_filtered_thu_list.sort_values('Listingid_List')
    noun_sentence_df_T_ri_filtered_thu_list = noun_sentence_df_T_ri_filtered_thu_list.rename(columns={'Listingid_List':'listingid'})
    
    noun_sentence_df_T_ri_filtered_thu_list = noun_sentence_df_T_ri_filtered_thu_list.drop_duplicates()
    
    file_join = file.split('.')[0] +'_noun_sentences_by_listingid_CJ.fea'
    noun_sentence_df_T_ri_filtered_thu_list.to_csv(file_join)

new_avm_df__full_data_state_KS_noun_sentences.fea
195440
new_avm_df__full_data_state_AZ_noun_sentences.fea
249275
new_avm_df__full_data_state_TN_noun_sentences.fea
371795
new_avm_df__full_data_state_FL_noun_sentences.fea
3360456
new_avm_df__full_data_state_GA_noun_sentences.fea
1070334
new_avm_df__full_data_state_OK_noun_sentences.fea
282297
new_avm_df__full_data_state_UT_noun_sentences.fea
350350
new_avm_df__full_data_state_ME_noun_sentences.fea
3
new_avm_df__full_data_state_CA_noun_sentences.fea
3276
new_avm_df__full_data_state_MS_noun_sentences.fea
41705
new_avm_df__full_data_state_WA_noun_sentences.fea
639656
new_avm_df__full_data_state_OH_noun_sentences.fea
464983
new_avm_df__full_data_state_MA_noun_sentences.fea
88
new_avm_df__full_data_state_AL_noun_sentences.fea
36555
new_avm_df__full_data_state_NC_noun_sentences.fea
902825
new_avm_df__full_data_state_CO_noun_sentences.fea
865913
new_avm_df__full_data_state_MO_noun_sentences.fea
583057
new_avm_df__full_data_state_KY_noun_sentences.fea
176694
new_avm_df__full_data_state_NE_noun_sentences.fea
8
new_avm_df__full_data_state_NY_noun_sentences.fea
35
new_avm_df__full_data_state_VA_noun_sentences.fea
25
new_avm_df__full_data_state_MD_noun_sentences.fea
13
new_avm_df__full_data_state_HI_noun_sentences.fea
21
new_avm_df__full_data_state_WV_noun_sentences.fea
62
new_avm_df__full_data_state_MN_noun_sentences.fea
21
new_avm_df__full_data_state_AK_noun_sentences.fea
16
new_avm_df__full_data_state_IN_noun_sentences.fea
177929
new_avm_df__full_data_state_PA_noun_sentences.fea
51
new_avm_df__full_data_state_SC_noun_sentences.fea
89425
new_avm_df__full_data_state_LA_noun_sentences.fea
8
new_avm_df__full_data_state_NJ_noun_sentences.fea
21
new_avm_df__full_data_state_RI_noun_sentences.fea
16
new_avm_df__full_data_state_WY_noun_sentences.fea
15
new_avm_df__full_data_state_TX_noun_sentences.fea
1978947

In [ ]:
for file in filtered_files[29:]:
    print(file)

In [58]:
noun_sentence_df_T_ri_filtered

Empty DataFrame
Columns: [noun_sentence, count, AVM_Error, AVM_Error_List, Listing_Error, Listing_Error_List, Listingid_List, AVM_Error_Average, Listing_Error_Average, AVM_Error_Indicators, Listing_Error_Indicators]
Index: []

In [40]:
noun_sentence_df_T_ri_filtered

,noun_sentence,count,AVM_Error,AVM_Error_List,Listing_Error,Listing_Error_List,Listingid_List,AVM_Error_Average,Listing_Error_Average,AVM_Error_Indicators,Listing_Error_Indicators,noun_sentence_corrections
10663,new custom baths w/ tile,25,4.913696,"[0.2041903235257364, 0.19063896710049413, 0.34...",-0.194580,"[-0.0664, -0.044, -0.024222704266088215, 0.052...","[195999293, 153928072, 226031070, 234295409, 2...",0.196548,-0.007783,"[0.19654782020325356, 0.015447080420365335, -0...","[-0.007783183831505435, 0.0009538049303427061,...",new custom baths with tile
13786,picky buyers,30,5.138048,"[0.22915100598340848, -0.03910519962264799, 0....",-0.715725,"[0.13067632850241545, 0.027777777777777776, 0....","[250039891, 227747430, 267559115, 201110062, 2...",0.171268,-0.023857,"[0.17126827795654045, 0.03469990680888714, 0.4...","[-0.023857485293342133, 0.011576446818672845, ...",picky buyers
14159,top bottom remodel,46,7.746796,"[0.4459542440747873, 0.2041903235257364, 0.143...",-0.378070,"[-0.010903314318723373, -0.0664, 0.02173913043...","[212422845, 195999293, 210459755, 153928072, 2...",0.168409,-0.008219,"[0.16840859841843328, 0.015028152960585182, 0....","[-0.00821891045578791, 0.002608665323521656, -...",top bottom remodel
16201,high end finishes,36,5.602091,"[0.4621233637010722, 0.6880820463893134, 0.080...",-0.692577,"[-0.06622222222222222, -0.00727891156462585, 0...","[176554461, 233930053, 250039987, 212077042, 2...",0.155614,-0.019238,"[0.1556136441157381, 0.054348849978394106, 1.3...","[-0.01923824655231468, 0.0053295532099018605, ...",high end finishes
19953,full remodel,21,2.873193,"[0.1643956266245036, 0.15664420706203896, 0.33...",-0.086433,"[0.0, -0.1219809709685289, -0.0126582278481012...","[133021704, 233370202, 227580822, 245642626, 2...",0.136819,-0.004116,"[0.13681869276657221, 0.0645496221912841, -2.0...","[-0.004115859637629247, 0.004537321266982855, ...",full remodel
...,...,...,...,...,...,...,...,...,...,...,...,...
191756,home needs work,22,-7.932432,"[-0.6662248428037519, 0.10589481758315536, -0....",-1.012763,"[0.22413793103448276, 0.03277807630306287, 0.0...","[210108268, 211911447, 227972166, 248926366, 2...",-0.360565,-0.046035,"[-0.3605650956776606, 0.15015708651946216, -1....","[-0.046034686625879194, 0.02258467814073249, -...",home needs work
191853,as-is condition,22,-8.041127,"[-0.20761758415185946, -0.04141008010864359, -...",-0.488933,"[0.03142857142857143, 0.026422764227642278, 0....","[215125394, 127047872, 225191065, 227515586, 1...",-0.365506,-0.022224,"[-0.3655057569665772, 0.2694466311439361, -1.9...","[-0.022224242978447214, 0.01044886693792336, -...",as-is condition
192619,great investment opportunity,33,-13.335261,"[-0.21907706088499707, -0.030522835982447333, ...",-3.271411,"[-0.02631578947368421, -0.008851124092759781, ...","[178382941, 225519422, 227274816, 266941595, 2...",-0.404099,-0.099134,"[-0.40409880733698444, 0.19031979382430186, -0...","[-0.09913365906829909, 0.03351086772208485, -1...",great investment opportunity
193327,short sale,21,-9.746415,"[-0.17488830142710435, -0.832710729633369, -0....",-1.238449,"[0.0, -0.1111111111111111, 0.0, 0.0, -0.073170...","[187325264, 133024449, 186510770, 198103715, 2...",-0.464115,-0.058974,"[-0.46411501470080807, 0.15962207653508392, -0...","[-0.05897377940015805, 0.042212788273870226, -...",short sale
193600,needs work,23,-11.205749,"[-0.2999618710008658, -0.5180114515454304, -0....",-1.580391,"[-0.24963235294117647, 0.10413793103448275, -0...","[212527242, 195649553, 245971222, 245562877, 2...",-0.487206,-0.068713,"[-0.4872064830631104, 0.1755959013421315, -1.7...","[-0.06871265406311636, 0.027534310326496468, -...",needs work

In [ ]:
9711296

In [46]:
noun_sentence_df_T_ri_filtered_thu = noun_sentence_df_T_ri_filtered.loc[:,['noun_sentence','Listingid_List']]

In [47]:
noun_sentence_df_T_ri_filtered_thu

,noun_sentence,Listingid_List
162046,new bathrooms,"[226771172, 226894344, 226798752, 226705586, 2..."
191942,measurements approximate,"[226789511, 226972662, 227216981, 227220287, 2..."
204925,top bottom,"[226874336, 227335468, 227067931, 227204798, 2..."
207082,quartz countertops,"[227126688, 227163953, 227060322, 227137424, 2..."
225617,new cabinets,"[226894344, 226755849, 226967145, 226807551, 2..."
...,...,...
808440,great potential,"[227171512, 227359007, 228392861, 228820100, 2..."
809053,major interstates,"[227154427, 226931146, 227598976, 229566962, 2..."
812573,great investment property,"[226801678, 226766720, 227620770, 227835706, 2..."
822110,needs tlc,"[10193559, 228298342, 231697221, 233081549, 23..."
825132,right redemption,"[226766720, 43307986, 175819212, 187496529, 18..."

In [48]:
noun_sentence_df_T_ri_filtered_thu_list = explode(noun_sentence_df_T_ri_filtered_thu,
                                           lst_cols=['Listingid_List'])

In [49]:
noun_sentence_df_T_ri_filtered_thu_list

            noun_sentence  Listingid_List
0           new bathrooms       226771172
1           new bathrooms       226894344
2           new bathrooms       226798752
3           new bathrooms       226705586
4           new bathrooms       226773117
...                   ...             ...
1128967  right redemption        10173537
1128968  right redemption        83277261
1128969  right redemption        10176800
1128970  right redemption        10303984
1128971  right redemption        10171719

[1128972 rows x 2 columns]